#image: "rust:latest" # "cimg/rust:1.65.0-node"
stages:
  - build
  - release

build-linux:
  stage: build
  image: "cimg/rust:1.65.0-node"
  script:
    - apt-get update -yqq
    - apt-get install -yqq --no-install-recommends build-essential libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev
    - npm install
    - npm run build
  artifacts:
    paths:
      - src-tauri/target/release/bundle/deb/*.deb
      - src-tauri/target/release/bundle/appimage/*.AppImage
#  rules:
#    - if: $CI_COMMIT_TAG

build-windows:
  stage: build
  image: apemill/tauri:latest
  # Be sure to select worker with `executor = "docker-windows"`
  #tags:
  #  - windows
  script:
    - yarn
    - yarn tauri build
    - $Env:FILE_NAME=$(Get-ChildItem c:\target\release\bundle\msi\*.msi | Select-Object -ExpandProperty Name)
    - Move-Item -Path "c:\target\release\bundle\msi\$Env:FILE_NAME" -Destination ".\Plan2Go_desktop-$TAG.msi"
  cache:
    key: shared-cache
    paths:
        - c:\target\
  artifacts:
    paths:
      - .\Plan2Go_desktop-$TAG.msi

#build-windows:
#  stage: build
#  image: "mcr.microsoft.com/windows:ltsc2019"
#  script:
#    - winget install --id Rustlang.Rustup
#    - npm install
#    - npm run build
#  artifacts:
#    paths:
#      - src-tauri/target/release/bundle/msi/*.msi
#  rules:
#    - if: $CI_COMMIT_TAG

#build-mac:
#  stage: build
#  image: "sickcodes/docker-osx:latest"
#  script:
#    - xcode-select --install
#    - curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh
#    - npm install
#    - npm run build
#  artifacts:
#    paths:
#      - src-tauri/target/release/bundle/msi/*.msi
#  rules:
#    - if: $CI_COMMIT_TAG

release:
  stage: release
  image: "rust:latest"
  script:
    - apt-get update -yqq
    - apt-get install -yqq --no-install-recommends build-essential nodejs npm libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev
    - npm install
    - npm run build
  artifacts:
    paths:
      - src-tauri/target/release/bundle/deb/*.deb
      - src-tauri/target/release/bundle/appimage/*.AppImage
      - src-tauri/target/release/bundle/msi/*.msi
  rules:
    - if: $CI_COMMIT_TAG
