##################################################
#     This file is now no longer being used!     #
#                                                #
# Go to Github version for the automated builds  # 
# https://github.com/TheDutchProgrammers/Plan2Go #
##################################################


#image: "rust:latest" # "cimg/rust:1.65.0-node"
stages:
  - build
  - secondtry_build

build-linux:
  stage: build
  image: "cimg/rust:1.65.0-node"
  script:
    - sudo apt-get update -yqq # sudo for cimg/rust
    - sudo apt-get install -yqq --no-install-recommends build-essential libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev file
    - npm install
    - npm run tauri build # -- --verbose
  cache:
    key: shared-cache
    paths:
      - src-tauri/target/
  artifacts:
    paths:
      - src-tauri/target/release/bundle/deb/*.deb
      - src-tauri/target/release/bundle/appimage/*.AppImage
  rules:
    - if: $CI_COMMIT_TAG

#build-windows:
#  stage: build
#  image: "mcr.microsoft.com/windows:ltsc2019"
#  script:
#    - winget install --id Rustlang.Rustup
#    - npm install
#    - npm run build
#  artifacts:
#    paths:
#      - src-tauri/target/release/bundle/msi/*.msi
#  rules:
#    - if: $CI_COMMIT_TAG

#build-mac:
#  stage: build
#  image: "sickcodes/docker-osx:latest"
#  script:
#    - xcode-select --install
#    - curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh
#    - npm install
#    - npm run build
#  artifacts:
#    paths:
#      - src-tauri/target/release/bundle/*/*.*
#  rules:
#    - if: $CI_COMMIT_TAG

build-linux-2:
  stage: secondtry_build
  image: "rust:latest"
  script:
    - apt-get update -yqq
    - apt-get install -yqq --no-install-recommends build-essential nodejs npm libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev
    - npm install
    - npm run build
  artifacts:
    paths:
      - src-tauri/target/release/bundle/deb/*.deb
      - src-tauri/target/release/bundle/appimage/*.AppImage
  cache:
    key: shared-cache
    paths:
      - src-tauri/target/
  rules:
    - if: $CI_COMMIT_TAG
  when: on_failure
