name: Build Mobile

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Android:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential curl wget libssl-dev libgtk-3-dev webkit2gtk-4.0 libayatana-appindicator3-dev librsvg2-dev patchelf libwebkit2gtk-4.0-dev
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11' 
    - name: Clone tauri next branch
      run: |
        git clone -b next https://github.com/tauri-apps/tauri
    - name: Build tauri next branch
      run: |
        cd tauri/tooling/cli
        cargo build
    - name: Cache tauri next branch
      uses: Swatinem/rust-cache@v2
      with:
          workspaces: "tauri/tooling/cli/"
    - name: Setup NDK 
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r25b
        local-cache: true
    - name: Rust target
      run: rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android
    - name: install app dependencies 
      run:  yarn
    - name: Cache build
      uses: Swatinem/rust-cache@v2
    - name: Init Android Studio Project
      run: tauri/tooling/cli/target/debug/cargo-tauri android init
      env:
        NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
    - name: Build apk
      run: tauri/tooling/cli/target/debug/cargo-tauri android build --split-per-abi --debug
      env:
        NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
    - uses: actions/upload-artifact@v3
      with:
        name: apks
        path: |
          src-tauri/gen/android/*/app/build/outputs/apk/**/**/*.apk
          
  IOS:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Build tauri next branch
      run: |
        git clone -b next https://github.com/tauri-apps/tauri
        cd tauri/tooling/cli/node
        yarn
        yarn build
    - name: Rust target
      run: rustup target add aarch64-apple-ios x86_64-apple-ios aarch64-apple-ios-sim
    - name: install app dependencies and build it
      run: yarn # && yarn build
    - name: Init Xcode Project
      run: yarn tauri ios init
    - name: Build IOS app
      run: yarn tauri ios build

