name: Build Mobile

on:
  push:
    branches: [ "test_DISABLED" ]
  pull_request:
    branches: [ "test_DISABLED" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  mobile:
    strategy:
      fail-fast: false
      matrix:
        platform: []
        include:
          - platform: ubuntu-22.04
            android: true
        #  - platform: macos-12 # disabled ios for now, cause it doesn't work (No code signing certificates found)
        #    ios: true
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      if: matrix.platform == 'ubuntu-22.04'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential curl wget libssl-dev libgtk-3-dev webkit2gtk-4.0 libayatana-appindicator3-dev librsvg2-dev patchelf libwebkit2gtk-4.0-dev
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Setup java
      uses: actions/setup-java@v3
      if: ${{ matrix.android }}
      with:
        distribution: 'temurin'
        java-version: '11' 
    - name: Clone tauri next branch
      if: ${{ matrix.android || matrix.ios }}
      run: |
        git clone -b next https://github.com/tauri-apps/tauri
    - name: Cache tauri next branch
      if: ${{ matrix.android || matrix.ios }}
      uses: Swatinem/rust-cache@v2
      with:
          workspaces: "tauri/tooling/cli/"
    - name: Build tauri next branch
      if: ${{ matrix.android || matrix.ios }}
      run: |
        cd tauri/tooling/cli
        cargo build
    - name: Setup NDK 
      if: ${{ matrix.android }}
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r25b
        local-cache: true
    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: './src-tauri -> target'
    - name: Android Rust target
      if: ${{ matrix.android }}
      run: rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android
    - name: ios Rust target
      if: ${{ matrix.ios }}
      run: rustup target add aarch64-apple-ios x86_64-apple-ios aarch64-apple-ios-sim
    - name: install app dependencies 
      run:  yarn
    - name: Init Android Studio Project
      if: ${{ matrix.android }}
      run: tauri/tooling/cli/target/debug/cargo-tauri android init
      env:
        NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
    - name: Init Xcode Project
      if: ${{ matrix.ios }}
      run: tauri/tooling/cli/target/debug/cargo-tauri ios init
    - name: Build apk
      if: ${{ matrix.android }}
      run: tauri/tooling/cli/target/debug/cargo-tauri android build --split-per-abi --debug
      env:
        NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
    - name: Build IOS app
      if: ${{ matrix.ios }}
      run: tauri/tooling/cli/target/debug/cargo-tauri ios build
    - uses: actions/upload-artifact@v3
      if: ${{ matrix.android }}
      with:
        name: apks
        path: |
          src-tauri/gen/android/app/app/build/outputs/apk/**/**/*.apk

